FROM build_container

RUN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

RUN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

UN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

UN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

UN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

UN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

UN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

UN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

UN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3

UN git clone https://github.com/cogent3/cogent3.git
RUN rm -rd cogent3


